name: task_list
description: Simple Task List App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  introduction_screen: ^2.1.0
  liquid_progress_indicator: ^0.4.0
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_ameno_ipsum: ^1.0.1
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true

  # Access .env file:
  ## import 'package:flutter_dotenv/flutter_dotenv.dart';
  ## dotenv.env['VAR_NAME'];
  assets:
    - assets/.env
    - assets/lang/
    - assets/images/launcher/app_icon.svg
    - assets/images/intro_screen/
    - assets/images/task_list_screen/

# Change app package name run:
## flutter pub run change_app_package_name:main com.new.package.name
# To change icon and splash run:
## flutter clean && flutter pub get
## flutter pub run flutter_native_splash:create && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path_android: "assets/images/launcher/icon_android.png"
  ios: true
  image_path_ios: "assets/images/launcher/icon_iphone.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/launcher/icon_splash.png
  color_dark: "#22252D"
  image_dark: assets/images/launcher/icon_splash.png
  android_disable_fullscreen: true
